server:
  port: 8080
  servlet:
    context-path: /real-estate
spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
      ssl.truststore.location: ${KAFKA_TRUSTSTORE_PATH}
      ssl.truststore.password: ${KAFKA_TRUSTSTORE_PASSWORD}
  datasource:
    # ===== SỬA: đổi sang biến môi trường để trỏ Aiven MySQL =====
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&requireSSL=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0
      connection-timeout: 5000
      ssl:
        enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: buingocdan2005@gmail.com
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB        # Giới hạn 5MB cho 1 file ảnh
      max-request-size: 20MB    # Giới hạn 20MB cho tổng 1 lần đăng tin (nhiều ảnh)
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_SECRET}
vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:8080/real-estate/payment/vnpay-callback"
jwt:
  signerKey: ${JWT_SIGNER_KEY}
  valid-duration: 1800 #second 30 phut
  refresh-duration: 604800 #second 1 tuan
ai:
  server:
    url: http://localhost:8000